#define resolucion 1024
#define numVerticesSJ 23
#define numVerticesHeredia 13
#define numVerticesCartago 13
#define numVerticesGuana 35
#define numVerticesAlajuela 23
#define numVerticesPuntaGolfo 11
#define numVerticesPunta 49
#define numVerticesLimon 29
